defaults:                           
  - model: eqmodel              
  - data: test_data_eqn         
pl_trainer:                         
  gpus: "3"                         
seed: 1234                          
processing_dir: './processing/test' 
checkpoint_path: ~                  
hydra:
  run:
    dir: ${processing_dir}          