# @package _group_
_target_: pl_igscmaes.data.dataset.RealPsFittingDataset
name: psmiami
bperp_dir: '/quobyte/dev_machine_learning/miami.tsx.sm_dsc.740.304.1500.1500/ifg_hr/'
bperp_ext: '.bperp'
ifg_dir: '/quobyte/dev_machine_learning/miami.tsx.sm_dsc.740.304.1500.1500/ifg_hr/'
ifg_ext: '.diff.orb.statm_cor.natm.filt'
filt_dir: '/quobyte/dev_machine_learning/miami.tsx.sm_dsc.740.304.1500.1500/ifg_hr/'
filt_ext: '.diff.orb.statm_cor.natm.filt'
coh_dir: '/quobyte/dev_machine_learning/miami.tsx.sm_dsc.740.304.1500.1500/ifg_hr/'
coh_ext: '.diff.orb.statm_cor.natm.filt.coh'
rslc_dir: '/quobyte/dev_machine_learning/miami.tsx.sm_dsc.740.304.1500.1500/rmli_hr/'
rslc_ext: '.rmli'
ref_mr_path: '/quobyte/dev_machine_learning/miami.tsx.sm_dsc.740.304.1500.1500/fit_hr/def_fit_cmpy'
ref_he_path: '/quobyte/dev_machine_learning/miami.tsx.sm_dsc.740.304.1500.1500/fit_hr/hgt_fit_m'
width: 1500 
height: 1500 
conv1: -0.0110745522839
conv2: -0.00160177996359
ps_coords_path: '/quobyte/dev_machine_learning/pf/igscmaes/ps/miami.tsx.sm_dsc/ps.json'
