defaults:                                                                           
  - model: eqmodel                                                                
  - data: train_data_eqn                                                         

pl_trainer:
  max_epochs: 50000                                                                                                                                
  gpus: "3"                                                                          
  val_check_interval: 100                                                     
  limit_val_batches: 5  
seed: 1234                                                                          
processing_dir: './processing/train'
hydra:
  run:
    dir: ${processing_dir}                                                        
