# @package _group_
_target_: model.equation_solve.EqModel    # __target__ is a one of the spacial feature of hydra .. That allow user to call any class and also run any function 
                                          #model= is the folder name , equation_solve = is the file name , EqModel =is the class name 
lr: 3e-4                    #learning rate
channels: 2                    #input channels
# loss_type: 'cosineSimilrity'         # Loss type. now we consider many loss functions so we dont fix any loss specifically
