defaults:
  - model: rbdn
  - data: mrcg1_real_single
pl_trainer:
  gpus: "3"
  max_epochs: 300
  # fast_dev_run: True
  val_check_interval: 506
  limit_val_batches: 1
  # accelerator: ddp
seed: 1234
processing_dir: './processing'
hydra:
  run:
    dir: ${processing_dir}
